#!/bin/sh
#
# chkconfig: 2345 99 01
# description: XKCD listener

case "$1" in
start)
	echo -n "Start service uberxkcd"
	su - oracle -c "/usr/java/jdk1.7.0_25/bin/java -jar /software/uberether/uberxkcd.jar" 2>&1 > /tmp/uberxkcd/service.log &
;;
stop)
	echo -n "Stop service uberxkcd"
	wget http://localhost:9000/uberxkcd/shutdown
	
	sleep 5

	status=""
	status=`netstat -tln|grep 9000|awk '{print $1}'`
        if [ -n "${status}" ] ;
        then
	   kill -9 `ps -ef |grep -v root | awk '/[u]berxkcd.jar/{print $2}'`
	fi
;;
restart)
	service uberxkcd stop
	service uberxkcd start
;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
;;
esac
